#### POST A LAUNCH

POST http://localhost:8000/launches
Content-Type: application/json

{
  "mission": "Kepler Exploration X",
  "rocket": "OLA",
  "destination": "Earth",
  "launchDate": "March 20, 2030"
}